//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientWebsite.BiblioService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UtilisateurAbonne", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class UtilisateurAbonne : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Numero {
            get {
                return this.NumeroField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroField, value) != true)) {
                    this.NumeroField = value;
                    this.RaisePropertyChanged("Numero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Livre", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Livre : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ISBNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitreField;
        
        private int NbExemplairesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuteurField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EditeurField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientWebsite.BiblioService.ArrayOfString CommentairesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ISBN {
            get {
                return this.ISBNField;
            }
            set {
                if ((this.ISBNField.Equals(value) != true)) {
                    this.ISBNField = value;
                    this.RaisePropertyChanged("ISBN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Titre {
            get {
                return this.TitreField;
            }
            set {
                if ((object.ReferenceEquals(this.TitreField, value) != true)) {
                    this.TitreField = value;
                    this.RaisePropertyChanged("Titre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int NbExemplaires {
            get {
                return this.NbExemplairesField;
            }
            set {
                if ((this.NbExemplairesField.Equals(value) != true)) {
                    this.NbExemplairesField = value;
                    this.RaisePropertyChanged("NbExemplaires");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Auteur {
            get {
                return this.AuteurField;
            }
            set {
                if ((object.ReferenceEquals(this.AuteurField, value) != true)) {
                    this.AuteurField = value;
                    this.RaisePropertyChanged("Auteur");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Editeur {
            get {
                return this.EditeurField;
            }
            set {
                if ((object.ReferenceEquals(this.EditeurField, value) != true)) {
                    this.EditeurField = value;
                    this.RaisePropertyChanged("Editeur");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public ClientWebsite.BiblioService.ArrayOfString Commentaires {
            get {
                return this.CommentairesField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentairesField, value) != true)) {
                    this.CommentairesField = value;
                    this.RaisePropertyChanged("Commentaires");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BiblioService.ServiceSoap")]
    public interface ServiceSoap {
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément getUtilisateursResult de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getUtilisateurs", ReplyAction="*")]
        ClientWebsite.BiblioService.getUtilisateursResponse getUtilisateurs(ClientWebsite.BiblioService.getUtilisateursRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément getLivresResult de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getLivres", ReplyAction="*")]
        ClientWebsite.BiblioService.getLivresResponse getLivres(ClientWebsite.BiblioService.getLivresRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément titre de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ajouterLivre", ReplyAction="*")]
        ClientWebsite.BiblioService.ajouterLivreResponse ajouterLivre(ClientWebsite.BiblioService.ajouterLivreRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément nom de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ajouterUtilisateurAbonne", ReplyAction="*")]
        ClientWebsite.BiblioService.ajouterUtilisateurAbonneResponse ajouterUtilisateurAbonne(ClientWebsite.BiblioService.ajouterUtilisateurAbonneRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément GetLivreByISBNResult de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLivreByISBN", ReplyAction="*")]
        ClientWebsite.BiblioService.GetLivreByISBNResponse GetLivreByISBN(ClientWebsite.BiblioService.GetLivreByISBNRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément auteur de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLivreByAuteur", ReplyAction="*")]
        ClientWebsite.BiblioService.GetLivreByAuteurResponse GetLivreByAuteur(ClientWebsite.BiblioService.GetLivreByAuteurRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément numero de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getUserById", ReplyAction="*")]
        ClientWebsite.BiblioService.getUserByIdResponse getUserById(ClientWebsite.BiblioService.getUserByIdRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément numero de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/utilisateurExist", ReplyAction="*")]
        ClientWebsite.BiblioService.utilisateurExistResponse utilisateurExist(ClientWebsite.BiblioService.utilisateurExistRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LivreExists", ReplyAction="*")]
        bool LivreExists(int isbn);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément commentaire de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ajouterCommentaire", ReplyAction="*")]
        ClientWebsite.BiblioService.ajouterCommentaireResponse ajouterCommentaire(ClientWebsite.BiblioService.ajouterCommentaireRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément livre de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getCommentairesByLivre", ReplyAction="*")]
        ClientWebsite.BiblioService.getCommentairesByLivreResponse getCommentairesByLivre(ClientWebsite.BiblioService.getCommentairesByLivreRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément numero de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/changeUserPassword", ReplyAction="*")]
        ClientWebsite.BiblioService.changeUserPasswordResponse changeUserPassword(ClientWebsite.BiblioService.changeUserPasswordRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément HelloWorldResult de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        ClientWebsite.BiblioService.HelloWorldResponse HelloWorld(ClientWebsite.BiblioService.HelloWorldRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUtilisateursRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getUtilisateurs", Namespace="http://tempuri.org/", Order=0)]
        public ClientWebsite.BiblioService.getUtilisateursRequestBody Body;
        
        public getUtilisateursRequest() {
        }
        
        public getUtilisateursRequest(ClientWebsite.BiblioService.getUtilisateursRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getUtilisateursRequestBody {
        
        public getUtilisateursRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUtilisateursResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getUtilisateursResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientWebsite.BiblioService.getUtilisateursResponseBody Body;
        
        public getUtilisateursResponse() {
        }
        
        public getUtilisateursResponse(ClientWebsite.BiblioService.getUtilisateursResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getUtilisateursResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ClientWebsite.BiblioService.UtilisateurAbonne[] getUtilisateursResult;
        
        public getUtilisateursResponseBody() {
        }
        
        public getUtilisateursResponseBody(ClientWebsite.BiblioService.UtilisateurAbonne[] getUtilisateursResult) {
            this.getUtilisateursResult = getUtilisateursResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getLivresRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getLivres", Namespace="http://tempuri.org/", Order=0)]
        public ClientWebsite.BiblioService.getLivresRequestBody Body;
        
        public getLivresRequest() {
        }
        
        public getLivresRequest(ClientWebsite.BiblioService.getLivresRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getLivresRequestBody {
        
        public getLivresRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getLivresResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getLivresResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientWebsite.BiblioService.getLivresResponseBody Body;
        
        public getLivresResponse() {
        }
        
        public getLivresResponse(ClientWebsite.BiblioService.getLivresResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getLivresResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ClientWebsite.BiblioService.Livre[] getLivresResult;
        
        public getLivresResponseBody() {
        }
        
        public getLivresResponseBody(ClientWebsite.BiblioService.Livre[] getLivresResult) {
            this.getLivresResult = getLivresResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ajouterLivreRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ajouterLivre", Namespace="http://tempuri.org/", Order=0)]
        public ClientWebsite.BiblioService.ajouterLivreRequestBody Body;
        
        public ajouterLivreRequest() {
        }
        
        public ajouterLivreRequest(ClientWebsite.BiblioService.ajouterLivreRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ajouterLivreRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string titre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string auteur;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string editeur;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int isbn;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int nbexemplaires;
        
        public ajouterLivreRequestBody() {
        }
        
        public ajouterLivreRequestBody(string titre, string auteur, string editeur, int isbn, int nbexemplaires) {
            this.titre = titre;
            this.auteur = auteur;
            this.editeur = editeur;
            this.isbn = isbn;
            this.nbexemplaires = nbexemplaires;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ajouterLivreResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ajouterLivreResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientWebsite.BiblioService.ajouterLivreResponseBody Body;
        
        public ajouterLivreResponse() {
        }
        
        public ajouterLivreResponse(ClientWebsite.BiblioService.ajouterLivreResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ajouterLivreResponseBody {
        
        public ajouterLivreResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ajouterUtilisateurAbonneRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ajouterUtilisateurAbonne", Namespace="http://tempuri.org/", Order=0)]
        public ClientWebsite.BiblioService.ajouterUtilisateurAbonneRequestBody Body;
        
        public ajouterUtilisateurAbonneRequest() {
        }
        
        public ajouterUtilisateurAbonneRequest(ClientWebsite.BiblioService.ajouterUtilisateurAbonneRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ajouterUtilisateurAbonneRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nom;
        
        public ajouterUtilisateurAbonneRequestBody() {
        }
        
        public ajouterUtilisateurAbonneRequestBody(string nom) {
            this.nom = nom;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ajouterUtilisateurAbonneResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ajouterUtilisateurAbonneResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientWebsite.BiblioService.ajouterUtilisateurAbonneResponseBody Body;
        
        public ajouterUtilisateurAbonneResponse() {
        }
        
        public ajouterUtilisateurAbonneResponse(ClientWebsite.BiblioService.ajouterUtilisateurAbonneResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ajouterUtilisateurAbonneResponseBody {
        
        public ajouterUtilisateurAbonneResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLivreByISBNRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLivreByISBN", Namespace="http://tempuri.org/", Order=0)]
        public ClientWebsite.BiblioService.GetLivreByISBNRequestBody Body;
        
        public GetLivreByISBNRequest() {
        }
        
        public GetLivreByISBNRequest(ClientWebsite.BiblioService.GetLivreByISBNRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetLivreByISBNRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int isbn;
        
        public GetLivreByISBNRequestBody() {
        }
        
        public GetLivreByISBNRequestBody(int isbn) {
            this.isbn = isbn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLivreByISBNResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLivreByISBNResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientWebsite.BiblioService.GetLivreByISBNResponseBody Body;
        
        public GetLivreByISBNResponse() {
        }
        
        public GetLivreByISBNResponse(ClientWebsite.BiblioService.GetLivreByISBNResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetLivreByISBNResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ClientWebsite.BiblioService.Livre GetLivreByISBNResult;
        
        public GetLivreByISBNResponseBody() {
        }
        
        public GetLivreByISBNResponseBody(ClientWebsite.BiblioService.Livre GetLivreByISBNResult) {
            this.GetLivreByISBNResult = GetLivreByISBNResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLivreByAuteurRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLivreByAuteur", Namespace="http://tempuri.org/", Order=0)]
        public ClientWebsite.BiblioService.GetLivreByAuteurRequestBody Body;
        
        public GetLivreByAuteurRequest() {
        }
        
        public GetLivreByAuteurRequest(ClientWebsite.BiblioService.GetLivreByAuteurRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetLivreByAuteurRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string auteur;
        
        public GetLivreByAuteurRequestBody() {
        }
        
        public GetLivreByAuteurRequestBody(string auteur) {
            this.auteur = auteur;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLivreByAuteurResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLivreByAuteurResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientWebsite.BiblioService.GetLivreByAuteurResponseBody Body;
        
        public GetLivreByAuteurResponse() {
        }
        
        public GetLivreByAuteurResponse(ClientWebsite.BiblioService.GetLivreByAuteurResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetLivreByAuteurResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ClientWebsite.BiblioService.Livre GetLivreByAuteurResult;
        
        public GetLivreByAuteurResponseBody() {
        }
        
        public GetLivreByAuteurResponseBody(ClientWebsite.BiblioService.Livre GetLivreByAuteurResult) {
            this.GetLivreByAuteurResult = GetLivreByAuteurResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUserByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getUserById", Namespace="http://tempuri.org/", Order=0)]
        public ClientWebsite.BiblioService.getUserByIdRequestBody Body;
        
        public getUserByIdRequest() {
        }
        
        public getUserByIdRequest(ClientWebsite.BiblioService.getUserByIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getUserByIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string numero;
        
        public getUserByIdRequestBody() {
        }
        
        public getUserByIdRequestBody(string numero) {
            this.numero = numero;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUserByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getUserByIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientWebsite.BiblioService.getUserByIdResponseBody Body;
        
        public getUserByIdResponse() {
        }
        
        public getUserByIdResponse(ClientWebsite.BiblioService.getUserByIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getUserByIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ClientWebsite.BiblioService.UtilisateurAbonne getUserByIdResult;
        
        public getUserByIdResponseBody() {
        }
        
        public getUserByIdResponseBody(ClientWebsite.BiblioService.UtilisateurAbonne getUserByIdResult) {
            this.getUserByIdResult = getUserByIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class utilisateurExistRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="utilisateurExist", Namespace="http://tempuri.org/", Order=0)]
        public ClientWebsite.BiblioService.utilisateurExistRequestBody Body;
        
        public utilisateurExistRequest() {
        }
        
        public utilisateurExistRequest(ClientWebsite.BiblioService.utilisateurExistRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class utilisateurExistRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string numero;
        
        public utilisateurExistRequestBody() {
        }
        
        public utilisateurExistRequestBody(string numero) {
            this.numero = numero;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class utilisateurExistResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="utilisateurExistResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientWebsite.BiblioService.utilisateurExistResponseBody Body;
        
        public utilisateurExistResponse() {
        }
        
        public utilisateurExistResponse(ClientWebsite.BiblioService.utilisateurExistResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class utilisateurExistResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool utilisateurExistResult;
        
        public utilisateurExistResponseBody() {
        }
        
        public utilisateurExistResponseBody(bool utilisateurExistResult) {
            this.utilisateurExistResult = utilisateurExistResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ajouterCommentaireRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ajouterCommentaire", Namespace="http://tempuri.org/", Order=0)]
        public ClientWebsite.BiblioService.ajouterCommentaireRequestBody Body;
        
        public ajouterCommentaireRequest() {
        }
        
        public ajouterCommentaireRequest(ClientWebsite.BiblioService.ajouterCommentaireRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ajouterCommentaireRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string commentaire;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public ClientWebsite.BiblioService.Livre livre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string numero;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string password;
        
        public ajouterCommentaireRequestBody() {
        }
        
        public ajouterCommentaireRequestBody(string commentaire, ClientWebsite.BiblioService.Livre livre, string numero, string password) {
            this.commentaire = commentaire;
            this.livre = livre;
            this.numero = numero;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ajouterCommentaireResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ajouterCommentaireResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientWebsite.BiblioService.ajouterCommentaireResponseBody Body;
        
        public ajouterCommentaireResponse() {
        }
        
        public ajouterCommentaireResponse(ClientWebsite.BiblioService.ajouterCommentaireResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ajouterCommentaireResponseBody {
        
        public ajouterCommentaireResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getCommentairesByLivreRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getCommentairesByLivre", Namespace="http://tempuri.org/", Order=0)]
        public ClientWebsite.BiblioService.getCommentairesByLivreRequestBody Body;
        
        public getCommentairesByLivreRequest() {
        }
        
        public getCommentairesByLivreRequest(ClientWebsite.BiblioService.getCommentairesByLivreRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getCommentairesByLivreRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ClientWebsite.BiblioService.Livre livre;
        
        public getCommentairesByLivreRequestBody() {
        }
        
        public getCommentairesByLivreRequestBody(ClientWebsite.BiblioService.Livre livre) {
            this.livre = livre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getCommentairesByLivreResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getCommentairesByLivreResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientWebsite.BiblioService.getCommentairesByLivreResponseBody Body;
        
        public getCommentairesByLivreResponse() {
        }
        
        public getCommentairesByLivreResponse(ClientWebsite.BiblioService.getCommentairesByLivreResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getCommentairesByLivreResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ClientWebsite.BiblioService.ArrayOfString getCommentairesByLivreResult;
        
        public getCommentairesByLivreResponseBody() {
        }
        
        public getCommentairesByLivreResponseBody(ClientWebsite.BiblioService.ArrayOfString getCommentairesByLivreResult) {
            this.getCommentairesByLivreResult = getCommentairesByLivreResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class changeUserPasswordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="changeUserPassword", Namespace="http://tempuri.org/", Order=0)]
        public ClientWebsite.BiblioService.changeUserPasswordRequestBody Body;
        
        public changeUserPasswordRequest() {
        }
        
        public changeUserPasswordRequest(ClientWebsite.BiblioService.changeUserPasswordRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class changeUserPasswordRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string numero;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string oldpass;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string newpass;
        
        public changeUserPasswordRequestBody() {
        }
        
        public changeUserPasswordRequestBody(string numero, string oldpass, string newpass) {
            this.numero = numero;
            this.oldpass = oldpass;
            this.newpass = newpass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class changeUserPasswordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="changeUserPasswordResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientWebsite.BiblioService.changeUserPasswordResponseBody Body;
        
        public changeUserPasswordResponse() {
        }
        
        public changeUserPasswordResponse(ClientWebsite.BiblioService.changeUserPasswordResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class changeUserPasswordResponseBody {
        
        public changeUserPasswordResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public ClientWebsite.BiblioService.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(ClientWebsite.BiblioService.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientWebsite.BiblioService.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(ClientWebsite.BiblioService.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : ClientWebsite.BiblioService.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<ClientWebsite.BiblioService.ServiceSoap>, ClientWebsite.BiblioService.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientWebsite.BiblioService.getUtilisateursResponse ClientWebsite.BiblioService.ServiceSoap.getUtilisateurs(ClientWebsite.BiblioService.getUtilisateursRequest request) {
            return base.Channel.getUtilisateurs(request);
        }
        
        public ClientWebsite.BiblioService.UtilisateurAbonne[] getUtilisateurs() {
            ClientWebsite.BiblioService.getUtilisateursRequest inValue = new ClientWebsite.BiblioService.getUtilisateursRequest();
            inValue.Body = new ClientWebsite.BiblioService.getUtilisateursRequestBody();
            ClientWebsite.BiblioService.getUtilisateursResponse retVal = ((ClientWebsite.BiblioService.ServiceSoap)(this)).getUtilisateurs(inValue);
            return retVal.Body.getUtilisateursResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientWebsite.BiblioService.getLivresResponse ClientWebsite.BiblioService.ServiceSoap.getLivres(ClientWebsite.BiblioService.getLivresRequest request) {
            return base.Channel.getLivres(request);
        }
        
        public ClientWebsite.BiblioService.Livre[] getLivres() {
            ClientWebsite.BiblioService.getLivresRequest inValue = new ClientWebsite.BiblioService.getLivresRequest();
            inValue.Body = new ClientWebsite.BiblioService.getLivresRequestBody();
            ClientWebsite.BiblioService.getLivresResponse retVal = ((ClientWebsite.BiblioService.ServiceSoap)(this)).getLivres(inValue);
            return retVal.Body.getLivresResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientWebsite.BiblioService.ajouterLivreResponse ClientWebsite.BiblioService.ServiceSoap.ajouterLivre(ClientWebsite.BiblioService.ajouterLivreRequest request) {
            return base.Channel.ajouterLivre(request);
        }
        
        public void ajouterLivre(string titre, string auteur, string editeur, int isbn, int nbexemplaires) {
            ClientWebsite.BiblioService.ajouterLivreRequest inValue = new ClientWebsite.BiblioService.ajouterLivreRequest();
            inValue.Body = new ClientWebsite.BiblioService.ajouterLivreRequestBody();
            inValue.Body.titre = titre;
            inValue.Body.auteur = auteur;
            inValue.Body.editeur = editeur;
            inValue.Body.isbn = isbn;
            inValue.Body.nbexemplaires = nbexemplaires;
            ClientWebsite.BiblioService.ajouterLivreResponse retVal = ((ClientWebsite.BiblioService.ServiceSoap)(this)).ajouterLivre(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientWebsite.BiblioService.ajouterUtilisateurAbonneResponse ClientWebsite.BiblioService.ServiceSoap.ajouterUtilisateurAbonne(ClientWebsite.BiblioService.ajouterUtilisateurAbonneRequest request) {
            return base.Channel.ajouterUtilisateurAbonne(request);
        }
        
        public void ajouterUtilisateurAbonne(string nom) {
            ClientWebsite.BiblioService.ajouterUtilisateurAbonneRequest inValue = new ClientWebsite.BiblioService.ajouterUtilisateurAbonneRequest();
            inValue.Body = new ClientWebsite.BiblioService.ajouterUtilisateurAbonneRequestBody();
            inValue.Body.nom = nom;
            ClientWebsite.BiblioService.ajouterUtilisateurAbonneResponse retVal = ((ClientWebsite.BiblioService.ServiceSoap)(this)).ajouterUtilisateurAbonne(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientWebsite.BiblioService.GetLivreByISBNResponse ClientWebsite.BiblioService.ServiceSoap.GetLivreByISBN(ClientWebsite.BiblioService.GetLivreByISBNRequest request) {
            return base.Channel.GetLivreByISBN(request);
        }
        
        public ClientWebsite.BiblioService.Livre GetLivreByISBN(int isbn) {
            ClientWebsite.BiblioService.GetLivreByISBNRequest inValue = new ClientWebsite.BiblioService.GetLivreByISBNRequest();
            inValue.Body = new ClientWebsite.BiblioService.GetLivreByISBNRequestBody();
            inValue.Body.isbn = isbn;
            ClientWebsite.BiblioService.GetLivreByISBNResponse retVal = ((ClientWebsite.BiblioService.ServiceSoap)(this)).GetLivreByISBN(inValue);
            return retVal.Body.GetLivreByISBNResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientWebsite.BiblioService.GetLivreByAuteurResponse ClientWebsite.BiblioService.ServiceSoap.GetLivreByAuteur(ClientWebsite.BiblioService.GetLivreByAuteurRequest request) {
            return base.Channel.GetLivreByAuteur(request);
        }
        
        public ClientWebsite.BiblioService.Livre GetLivreByAuteur(string auteur) {
            ClientWebsite.BiblioService.GetLivreByAuteurRequest inValue = new ClientWebsite.BiblioService.GetLivreByAuteurRequest();
            inValue.Body = new ClientWebsite.BiblioService.GetLivreByAuteurRequestBody();
            inValue.Body.auteur = auteur;
            ClientWebsite.BiblioService.GetLivreByAuteurResponse retVal = ((ClientWebsite.BiblioService.ServiceSoap)(this)).GetLivreByAuteur(inValue);
            return retVal.Body.GetLivreByAuteurResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientWebsite.BiblioService.getUserByIdResponse ClientWebsite.BiblioService.ServiceSoap.getUserById(ClientWebsite.BiblioService.getUserByIdRequest request) {
            return base.Channel.getUserById(request);
        }
        
        public ClientWebsite.BiblioService.UtilisateurAbonne getUserById(string numero) {
            ClientWebsite.BiblioService.getUserByIdRequest inValue = new ClientWebsite.BiblioService.getUserByIdRequest();
            inValue.Body = new ClientWebsite.BiblioService.getUserByIdRequestBody();
            inValue.Body.numero = numero;
            ClientWebsite.BiblioService.getUserByIdResponse retVal = ((ClientWebsite.BiblioService.ServiceSoap)(this)).getUserById(inValue);
            return retVal.Body.getUserByIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientWebsite.BiblioService.utilisateurExistResponse ClientWebsite.BiblioService.ServiceSoap.utilisateurExist(ClientWebsite.BiblioService.utilisateurExistRequest request) {
            return base.Channel.utilisateurExist(request);
        }
        
        public bool utilisateurExist(string numero) {
            ClientWebsite.BiblioService.utilisateurExistRequest inValue = new ClientWebsite.BiblioService.utilisateurExistRequest();
            inValue.Body = new ClientWebsite.BiblioService.utilisateurExistRequestBody();
            inValue.Body.numero = numero;
            ClientWebsite.BiblioService.utilisateurExistResponse retVal = ((ClientWebsite.BiblioService.ServiceSoap)(this)).utilisateurExist(inValue);
            return retVal.Body.utilisateurExistResult;
        }
        
        public bool LivreExists(int isbn) {
            return base.Channel.LivreExists(isbn);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientWebsite.BiblioService.ajouterCommentaireResponse ClientWebsite.BiblioService.ServiceSoap.ajouterCommentaire(ClientWebsite.BiblioService.ajouterCommentaireRequest request) {
            return base.Channel.ajouterCommentaire(request);
        }
        
        public void ajouterCommentaire(string commentaire, ClientWebsite.BiblioService.Livre livre, string numero, string password) {
            ClientWebsite.BiblioService.ajouterCommentaireRequest inValue = new ClientWebsite.BiblioService.ajouterCommentaireRequest();
            inValue.Body = new ClientWebsite.BiblioService.ajouterCommentaireRequestBody();
            inValue.Body.commentaire = commentaire;
            inValue.Body.livre = livre;
            inValue.Body.numero = numero;
            inValue.Body.password = password;
            ClientWebsite.BiblioService.ajouterCommentaireResponse retVal = ((ClientWebsite.BiblioService.ServiceSoap)(this)).ajouterCommentaire(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientWebsite.BiblioService.getCommentairesByLivreResponse ClientWebsite.BiblioService.ServiceSoap.getCommentairesByLivre(ClientWebsite.BiblioService.getCommentairesByLivreRequest request) {
            return base.Channel.getCommentairesByLivre(request);
        }
        
        public ClientWebsite.BiblioService.ArrayOfString getCommentairesByLivre(ClientWebsite.BiblioService.Livre livre) {
            ClientWebsite.BiblioService.getCommentairesByLivreRequest inValue = new ClientWebsite.BiblioService.getCommentairesByLivreRequest();
            inValue.Body = new ClientWebsite.BiblioService.getCommentairesByLivreRequestBody();
            inValue.Body.livre = livre;
            ClientWebsite.BiblioService.getCommentairesByLivreResponse retVal = ((ClientWebsite.BiblioService.ServiceSoap)(this)).getCommentairesByLivre(inValue);
            return retVal.Body.getCommentairesByLivreResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientWebsite.BiblioService.changeUserPasswordResponse ClientWebsite.BiblioService.ServiceSoap.changeUserPassword(ClientWebsite.BiblioService.changeUserPasswordRequest request) {
            return base.Channel.changeUserPassword(request);
        }
        
        public void changeUserPassword(string numero, string oldpass, string newpass) {
            ClientWebsite.BiblioService.changeUserPasswordRequest inValue = new ClientWebsite.BiblioService.changeUserPasswordRequest();
            inValue.Body = new ClientWebsite.BiblioService.changeUserPasswordRequestBody();
            inValue.Body.numero = numero;
            inValue.Body.oldpass = oldpass;
            inValue.Body.newpass = newpass;
            ClientWebsite.BiblioService.changeUserPasswordResponse retVal = ((ClientWebsite.BiblioService.ServiceSoap)(this)).changeUserPassword(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientWebsite.BiblioService.HelloWorldResponse ClientWebsite.BiblioService.ServiceSoap.HelloWorld(ClientWebsite.BiblioService.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            ClientWebsite.BiblioService.HelloWorldRequest inValue = new ClientWebsite.BiblioService.HelloWorldRequest();
            inValue.Body = new ClientWebsite.BiblioService.HelloWorldRequestBody();
            ClientWebsite.BiblioService.HelloWorldResponse retVal = ((ClientWebsite.BiblioService.ServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
    }
}
